language: ruby
rvm:
  - 2.3.0
gemfile:
  - gemfiles/rails-3.2
  - gemfiles/rails-4.0
  - gemfiles/rails-4.0-jasmine-2
  - gemfiles/rails-4.1
  - gemfiles/rails-5.0
  - gemfiles/rails-5-sprockets-4
  - gemfiles/rails-5.2
cache:
  directories:
    - /home/travis/.phantomjs
sudo: false
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

script: './run-tests.rb'
